-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

CREATE TABLE public.student (
    school text,
    sex text,
    age integer,
    address text,
    famsize text,
    "Pstatus" text,
    "Medu" integer,
    "Fedu" integer,
    "Mjob" text,
    "Fjob" text,
    reason text,
    guardian text,
    traveltime integer,
    studytime integer,
    failures integer,
    schoolsup text,
    famsup text,
    paid text,
    activities text,
    nursery text,
    higher text,
    internet text,
    romantic text,
    famrel integer,
    freetime integer,
    goout integer,
    "Dalc" integer,
    "Walc" integer,
    health integer,
    absences integer,
    "G1" integer,
    "G2" integer,
    "G3" integer
);
